//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapon
    {
        public int Id { get; set; }
        public string Trunk { get; set; }
        public string Caliber { get; set; }
        public string Type { get; set; }
        public string Country { get; set; }
        public string Material { get; set; }
        public Nullable<bool> pikatini { get; set; }
        public Nullable<bool> Bulpup { get; set; }
        public Nullable<int> Magazine_Size { get; set; }
    }
}
